name: shop_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl:
  fluttertoast:
  equatable:
  flutter_bloc:
  dartz:
  internet_connection_checker:
  shared_preferences:
  get_it:
  dio:
#  flutter_spinkit:
  carousel_slider:
  cached_network_image:



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true # Add this line
  uses-material-design: true

  assets:
    - assets/img/
#     - images/a_dot_ham.jpeg

#   example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
